services:
  backend:
    build: ./backend
    container_name: kanban_backend
    environment:
      - DB_HOST=${DB_HOST}
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASS=${DB_PASS}
      - JWT_SECRET=${JWT_SECRET}
      - FILE_UPLOAD_DIR=/data/uploads
    volumes:
      - backend_data:/data
    ports:
      - "8085:8080"
    depends_on: []
  frontend:
    build: ./frontend
    container_name: kanban_frontend
    environment:
      - VITE_API_BASE=http://10.3.70.107:8085/api
    ports:
      - "5174:5173"
    depends_on:
      - backend
volumes:
  backend_data:
